### ISSUE TITLE
Lack of pull requests

### ISSUE THREAD

**Issue by ogryzek** [christianarab/competition_cats#3]
There seems to be a lack of pull requests, and/or branches with current commits!

🍡

**Comment by christianarab** [comment]
Hi Drew, thanks for raising this issue. I have some household tasks that I have committed myself to. Will make more soon late at night and early tomorrow. Thanks again!

**Comment by christianarab** [comment]
https://github.com/christianarab/competition_cats/pull/4 

guilt is fuel for christian

**Comment by christianarab** [comment]
https://github.com/christianarab/competition_cats/pull/5
